import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import homeStyles from '../styles/Home.module.css';
import {getSortedPostsData} from '../lib/post'
import type{GetStaticProps, NextPage} from 'next'
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const Home = ({allPostsData}: {
  allPostsData: {
    date: string
    title: string
    id: string
  }[]
}) => {
  return (
    <div className={homeStyles.container}>
      <Head>
        <title>Bon Heon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={homeStyles.headingMd}>
        <p>[Bon Heon Introduction]</p>
        <p>
          (This is a website)
        </p>
      </section>
      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}>
          {allPostsData.map((
            {id, title, date}) =>
          <li className={homeStyles.listItem} key={id}>
            <Link href={`/posts/${id}` } legacyBehavior>
              <a>{title}</a>
            </Link>
            <br />
            <small className={homeStyles.lightText}>
              {date}
            </small>
          </li>
          )}
        </ul>
      </section>
      
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props : {
      allPostsData
    }
  }
}


export default Home;